@baseURL=https://frozen-headland-66513.herokuapp.com
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MTU2YzA4YjAwZmRjNWQ3NGZiMGNkMmQiLCJlbWFpbCI6ImJhZEBkb2UuY29tIiwiaWF0IjoxNjM0MDMxMTg5LCJleHAiOjE2MzQ2MzU5ODl9.2phd0Q2buOlOEtVc2ExPhD-HBpBObFNgosfeGHDW8No
### Get cabins
GET {{baseURL}}/cabins
Authorization: Barer {{token}}

### Login to Cabins
POST {{baseURL}}/users/login
Content-Type: application/json

{ "email": "bad@doe.com", "password": "password123" }