#@remoteURL=https://nameless-shore-55233.herokuapp.com/
@remoteURL=http://127.0.0.1:5000

### GET, Get all users
GET {{remoteURL}}

### POST, Create new user
POST {{remoteURL}}/orders
Content-Type: application/json

{   
    "cabin": "Jane's Cabbe",
    "service": "Dusting",
    "email": "jane@doe.com"
}